// Tropiki Stage 2: self-contained recipe normalization.
// This file deliberately does not depend on global config objects.
// KubeJS: 2101.7.2 / Minecraft 1.21.1 NeoForge

ServerEvents.recipes(function (event) {
  // --- ZEN's Upgraded Netherite: keep exactly the 7 requested special items. ---
  var zenRemoveOutputs = [
    'zens_upgraded_netherite:amber',
    'zens_upgraded_netherite:amber_block',
    'zens_upgraded_netherite:amber_ore',
    'zens_upgraded_netherite:amberite_axe',
    'zens_upgraded_netherite:amberite_boots',
    'zens_upgraded_netherite:amberite_chestplate',
    'zens_upgraded_netherite:amberite_elytra',
    'zens_upgraded_netherite:amberite_helmet',
    'zens_upgraded_netherite:amberite_hoe',
    'zens_upgraded_netherite:amberite_ingot',
    'zens_upgraded_netherite:amberite_leggings',
    'zens_upgraded_netherite:amberite_pickaxe',
    'zens_upgraded_netherite:amberite_shovel',
    'zens_upgraded_netherite:amberite_sword',
    'zens_upgraded_netherite:deepslate_amber_ore',
    'zens_upgraded_netherite:deepslate_fluorite_ore',
    'zens_upgraded_netherite:deepslate_onyx_ore',
    'zens_upgraded_netherite:deepslate_ruby_ore',
    'zens_upgraded_netherite:deepslate_sapphire_ore',
    'zens_upgraded_netherite:deepslate_topaz_ore',
    'zens_upgraded_netherite:emeraldite_axe',
    'zens_upgraded_netherite:emeraldite_boots',
    'zens_upgraded_netherite:emeraldite_chestplate',
    'zens_upgraded_netherite:emeraldite_elytra',
    'zens_upgraded_netherite:emeraldite_helmet',
    'zens_upgraded_netherite:emeraldite_hoe',
    'zens_upgraded_netherite:emeraldite_ingot',
    'zens_upgraded_netherite:emeraldite_leggings',
    'zens_upgraded_netherite:emeraldite_pickaxe',
    'zens_upgraded_netherite:emeraldite_shovel',
    'zens_upgraded_netherite:emeraldite_sword',
    'zens_upgraded_netherite:fluorisite_axe',
    'zens_upgraded_netherite:fluorisite_boots',
    'zens_upgraded_netherite:fluorisite_chestplate',
    'zens_upgraded_netherite:fluorisite_elytra',
    'zens_upgraded_netherite:fluorisite_helmet',
    'zens_upgraded_netherite:fluorisite_hoe',
    'zens_upgraded_netherite:fluorisite_ingot',
    'zens_upgraded_netherite:fluorisite_leggings',
    'zens_upgraded_netherite:fluorisite_pickaxe',
    'zens_upgraded_netherite:fluorisite_shovel',
    'zens_upgraded_netherite:fluorisite_sword',
    'zens_upgraded_netherite:fluorite',
    'zens_upgraded_netherite:fluorite_block',
    'zens_upgraded_netherite:fluorite_ore',
    'zens_upgraded_netherite:graviton',
    'zens_upgraded_netherite:mini_black_hole',
    'zens_upgraded_netherite:mini_white_hole',
    'zens_upgraded_netherite:netherite_anvil',
    'zens_upgraded_netherite:netherite_stick',
    'zens_upgraded_netherite:onyx',
    'zens_upgraded_netherite:onyx_block',
    'zens_upgraded_netherite:onyx_ore',
    'zens_upgraded_netherite:onyxerite_axe',
    'zens_upgraded_netherite:onyxerite_boots',
    'zens_upgraded_netherite:onyxerite_chestplate',
    'zens_upgraded_netherite:onyxerite_elytra',
    'zens_upgraded_netherite:onyxerite_helmet',
    'zens_upgraded_netherite:onyxerite_hoe',
    'zens_upgraded_netherite:onyxerite_ingot',
    'zens_upgraded_netherite:onyxerite_leggings',
    'zens_upgraded_netherite:onyxerite_pickaxe',
    'zens_upgraded_netherite:onyxerite_shovel',
    'zens_upgraded_netherite:onyxerite_sword',
    'zens_upgraded_netherite:ruby',
    'zens_upgraded_netherite:ruby_block',
    'zens_upgraded_netherite:ruby_ore',
    'zens_upgraded_netherite:rubycite_axe',
    'zens_upgraded_netherite:rubycite_boots',
    'zens_upgraded_netherite:rubycite_chestplate',
    'zens_upgraded_netherite:rubycite_elytra',
    'zens_upgraded_netherite:rubycite_helmet',
    'zens_upgraded_netherite:rubycite_hoe',
    'zens_upgraded_netherite:rubycite_ingot',
    'zens_upgraded_netherite:rubycite_leggings',
    'zens_upgraded_netherite:rubycite_pickaxe',
    'zens_upgraded_netherite:rubycite_shovel',
    'zens_upgraded_netherite:rubycite_sword',
    'zens_upgraded_netherite:rune_abyssal_tier_1',
    'zens_upgraded_netherite:rune_abyssal_tier_2',
    'zens_upgraded_netherite:rune_abyssal_tier_3',
    'zens_upgraded_netherite:rune_abyssal_tier_4',
    'zens_upgraded_netherite:rune_abyssal_tier_5',
    'zens_upgraded_netherite:rune_ember_tier_1',
    'zens_upgraded_netherite:rune_ember_tier_2',
    'zens_upgraded_netherite:rune_ember_tier_3',
    'zens_upgraded_netherite:rune_ember_tier_4',
    'zens_upgraded_netherite:rune_ember_tier_5',
    'zens_upgraded_netherite:rune_telluric_tier_1',
    'zens_upgraded_netherite:rune_telluric_tier_2',
    'zens_upgraded_netherite:rune_telluric_tier_3',
    'zens_upgraded_netherite:rune_telluric_tier_4',
    'zens_upgraded_netherite:rune_telluric_tier_5',
    'zens_upgraded_netherite:rune_vitality_tier_1',
    'zens_upgraded_netherite:rune_vitality_tier_2',
    'zens_upgraded_netherite:rune_vitality_tier_3',
    'zens_upgraded_netherite:rune_vitality_tier_4',
    'zens_upgraded_netherite:rune_vitality_tier_5',
    'zens_upgraded_netherite:sapphenite_axe',
    'zens_upgraded_netherite:sapphenite_boots',
    'zens_upgraded_netherite:sapphenite_chestplate',
    'zens_upgraded_netherite:sapphenite_elytra',
    'zens_upgraded_netherite:sapphenite_helmet',
    'zens_upgraded_netherite:sapphenite_hoe',
    'zens_upgraded_netherite:sapphenite_ingot',
    'zens_upgraded_netherite:sapphenite_leggings',
    'zens_upgraded_netherite:sapphenite_pickaxe',
    'zens_upgraded_netherite:sapphenite_shovel',
    'zens_upgraded_netherite:sapphenite_sword',
    'zens_upgraded_netherite:sapphire',
    'zens_upgraded_netherite:sapphire_block',
    'zens_upgraded_netherite:sapphire_ore',
    'zens_upgraded_netherite:singularite_axe',
    'zens_upgraded_netherite:singularite_boots',
    'zens_upgraded_netherite:singularite_chestplate',
    'zens_upgraded_netherite:singularite_elytra',
    'zens_upgraded_netherite:singularite_hammer',
    'zens_upgraded_netherite:singularite_helmet',
    'zens_upgraded_netherite:singularite_hoe',
    'zens_upgraded_netherite:singularite_ingot',
    'zens_upgraded_netherite:singularite_leggings',
    'zens_upgraded_netherite:singularite_pickaxe',
    'zens_upgraded_netherite:singularite_shovel',
    'zens_upgraded_netherite:singularite_sword',
    'zens_upgraded_netherite:topaz',
    'zens_upgraded_netherite:topaz_block',
    'zens_upgraded_netherite:topaz_ore',
    'zens_upgraded_netherite:topazite_axe',
    'zens_upgraded_netherite:topazite_boots',
    'zens_upgraded_netherite:topazite_chestplate',
    'zens_upgraded_netherite:topazite_elytra',
    'zens_upgraded_netherite:topazite_helmet',
    'zens_upgraded_netherite:topazite_hoe',
    'zens_upgraded_netherite:topazite_ingot',
    'zens_upgraded_netherite:topazite_leggings',
    'zens_upgraded_netherite:topazite_pickaxe',
    'zens_upgraded_netherite:topazite_shovel',
    'zens_upgraded_netherite:topazite_sword'
  ];

  for (var i = 0; i < zenRemoveOutputs.length; i++) {
    event.remove({ output: zenRemoveOutputs[i] });
  }

  // Remove recipe IDs already proven broken in this pack.
  // NOTE: malformed source JSON may still log a parse error before KubeJS sees it.
  var brokenRecipeIds = [
    'tf_dnv:composter',
    'tf_dnv:mycologist_table',
    'tf_dnv:mushgloom_torch',
    'tf_dnv:alchemy_table',
    'tf_dnv:lumber_table',
    'tf_dnv:butcher_table',
    'compatdelight:tropicraftdelight/coconut_milk',
    'compatdelight:cavebiomesdelight/icicle_knife',
    'compatdelight:cavebiomesdelight/glazed_frost_lily'
  ];

  for (var j = 0; j < brokenRecipeIds.length; j++) {
    event.remove({ id: brokenRecipeIds[j] });
  }

  // --- Coal <-> charcoal: recipes that explicitly request either one accept the common coal tag. ---
  // This does not delete either item and does not alter furnace production.
  event.replaceInput({ input: 'minecraft:coal' }, 'minecraft:coal', '#minecraft:coals');
  event.replaceInput({ input: 'minecraft:charcoal' }, 'minecraft:charcoal', '#minecraft:coals');
});
